spring:
    application:
        name: SpringBootBatch
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    batch:
        job:
            enable: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB


